/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface VanillaV1Uniswap02Interface extends ethers.utils.Interface {
  functions: {
    "isTokenRewarded(address)": FunctionFragment;
    "wethReserves(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "isTokenRewarded",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "wethReserves",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "isTokenRewarded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wethReserves",
    data: BytesLike
  ): Result;

  events: {};
}

export class VanillaV1Uniswap02 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: VanillaV1Uniswap02Interface;

  functions: {
    isTokenRewarded(
      token: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isTokenRewarded(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    wethReserves(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "wethReserves(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  isTokenRewarded(token: string, overrides?: CallOverrides): Promise<boolean>;

  "isTokenRewarded(address)"(
    token: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  wethReserves(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "wethReserves(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    isTokenRewarded(token: string, overrides?: CallOverrides): Promise<boolean>;

    "isTokenRewarded(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    wethReserves(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "wethReserves(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    isTokenRewarded(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isTokenRewarded(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    wethReserves(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "wethReserves(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    isTokenRewarded(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isTokenRewarded(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    wethReserves(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "wethReserves(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
