/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IVanillaV1Safelist01Interface extends ethers.utils.Interface {
  functions: {
    "isSafelisted(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "isSafelisted",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "isSafelisted",
    data: BytesLike
  ): Result;

  events: {
    "TokensAdded(address[])": EventFragment;
    "TokensRemoved(address[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TokensAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensRemoved"): EventFragment;
}

export class IVanillaV1Safelist01 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IVanillaV1Safelist01Interface;

  functions: {
    isSafelisted(token: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isSafelisted(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  isSafelisted(token: string, overrides?: CallOverrides): Promise<boolean>;

  "isSafelisted(address)"(
    token: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    isSafelisted(token: string, overrides?: CallOverrides): Promise<boolean>;

    "isSafelisted(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    TokensAdded(
      tokens: null
    ): TypedEventFilter<[string[]], { tokens: string[] }>;

    TokensRemoved(
      tokens: null
    ): TypedEventFilter<[string[]], { tokens: string[] }>;
  };

  estimateGas: {
    isSafelisted(token: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isSafelisted(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    isSafelisted(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isSafelisted(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
