/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface VanillaV1Router02Interface extends ethers.utils.Interface {
  functions: {
    "buy(address,uint256,uint256,uint256)": FunctionFragment;
    "depositAndBuy(address,uint256,uint256)": FunctionFragment;
    "epoch()": FunctionFragment;
    "estimateReward(address,address,uint256,uint256)": FunctionFragment;
    "safeList()": FunctionFragment;
    "sell(address,uint256,uint256,uint256)": FunctionFragment;
    "sellAndWithdraw(address,uint256,uint256,uint256)": FunctionFragment;
    "tokenPriceData(address,address)": FunctionFragment;
    "uniswapV3SwapCallback(int256,int256,bytes)": FunctionFragment;
    "vnlContract()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "buy",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositAndBuy",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "epoch", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "estimateReward",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "safeList", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellAndWithdraw",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenPriceData",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapV3SwapCallback",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vnlContract",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositAndBuy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "epoch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "estimateReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "safeList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sellAndWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenPriceData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV3SwapCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vnlContract",
    data: BytesLike
  ): Result;

  events: {
    "TokensPurchased(address,address,uint256,uint256)": EventFragment;
    "TokensSold(address,address,uint256,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TokensPurchased"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensSold"): EventFragment;
}

export class VanillaV1Router02 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: VanillaV1Router02Interface;

  functions: {
    buy(
      token: string,
      numEth: BigNumberish,
      numToken: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "buy(address,uint256,uint256,uint256)"(
      token: string,
      numEth: BigNumberish,
      numToken: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositAndBuy(
      token: string,
      numToken: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "depositAndBuy(address,uint256,uint256)"(
      token: string,
      numToken: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    epoch(overrides?: CallOverrides): Promise<[BigNumber]>;

    "epoch()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    estimateReward(
      owner: string,
      token: string,
      numEth: BigNumberish,
      numTokensSold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        profitablePrice: BigNumber;
        avgBlock: BigNumber;
        htrs: BigNumber;
        reward: BigNumber;
      }
    >;

    "estimateReward(address,address,uint256,uint256)"(
      owner: string,
      token: string,
      numEth: BigNumberish,
      numTokensSold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        profitablePrice: BigNumber;
        avgBlock: BigNumber;
        htrs: BigNumber;
        reward: BigNumber;
      }
    >;

    safeList(overrides?: CallOverrides): Promise<[string]>;

    "safeList()"(overrides?: CallOverrides): Promise<[string]>;

    sell(
      token: string,
      numToken: BigNumberish,
      numEthLimit: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "sell(address,uint256,uint256,uint256)"(
      token: string,
      numToken: BigNumberish,
      numEthLimit: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sellAndWithdraw(
      token: string,
      numToken: BigNumberish,
      numEthLimit: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "sellAndWithdraw(address,uint256,uint256,uint256)"(
      token: string,
      numToken: BigNumberish,
      numEthLimit: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tokenPriceData(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        ethSum: BigNumber;
        tokenSum: BigNumber;
        weightedBlockSum: BigNumber;
        latestBlock: BigNumber;
      }
    >;

    "tokenPriceData(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        ethSum: BigNumber;
        tokenSum: BigNumber;
        weightedBlockSum: BigNumber;
        latestBlock: BigNumber;
      }
    >;

    uniswapV3SwapCallback(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "uniswapV3SwapCallback(int256,int256,bytes)"(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    vnlContract(overrides?: CallOverrides): Promise<[string]>;

    "vnlContract()"(overrides?: CallOverrides): Promise<[string]>;
  };

  buy(
    token: string,
    numEth: BigNumberish,
    numToken: BigNumberish,
    blockTimeDeadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "buy(address,uint256,uint256,uint256)"(
    token: string,
    numEth: BigNumberish,
    numToken: BigNumberish,
    blockTimeDeadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositAndBuy(
    token: string,
    numToken: BigNumberish,
    blockTimeDeadline: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "depositAndBuy(address,uint256,uint256)"(
    token: string,
    numToken: BigNumberish,
    blockTimeDeadline: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  epoch(overrides?: CallOverrides): Promise<BigNumber>;

  "epoch()"(overrides?: CallOverrides): Promise<BigNumber>;

  estimateReward(
    owner: string,
    token: string,
    numEth: BigNumberish,
    numTokensSold: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      profitablePrice: BigNumber;
      avgBlock: BigNumber;
      htrs: BigNumber;
      reward: BigNumber;
    }
  >;

  "estimateReward(address,address,uint256,uint256)"(
    owner: string,
    token: string,
    numEth: BigNumberish,
    numTokensSold: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      profitablePrice: BigNumber;
      avgBlock: BigNumber;
      htrs: BigNumber;
      reward: BigNumber;
    }
  >;

  safeList(overrides?: CallOverrides): Promise<string>;

  "safeList()"(overrides?: CallOverrides): Promise<string>;

  sell(
    token: string,
    numToken: BigNumberish,
    numEthLimit: BigNumberish,
    blockTimeDeadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "sell(address,uint256,uint256,uint256)"(
    token: string,
    numToken: BigNumberish,
    numEthLimit: BigNumberish,
    blockTimeDeadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sellAndWithdraw(
    token: string,
    numToken: BigNumberish,
    numEthLimit: BigNumberish,
    blockTimeDeadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "sellAndWithdraw(address,uint256,uint256,uint256)"(
    token: string,
    numToken: BigNumberish,
    numEthLimit: BigNumberish,
    blockTimeDeadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tokenPriceData(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      ethSum: BigNumber;
      tokenSum: BigNumber;
      weightedBlockSum: BigNumber;
      latestBlock: BigNumber;
    }
  >;

  "tokenPriceData(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      ethSum: BigNumber;
      tokenSum: BigNumber;
      weightedBlockSum: BigNumber;
      latestBlock: BigNumber;
    }
  >;

  uniswapV3SwapCallback(
    amount0Delta: BigNumberish,
    amount1Delta: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "uniswapV3SwapCallback(int256,int256,bytes)"(
    amount0Delta: BigNumberish,
    amount1Delta: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  vnlContract(overrides?: CallOverrides): Promise<string>;

  "vnlContract()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    buy(
      token: string,
      numEth: BigNumberish,
      numToken: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "buy(address,uint256,uint256,uint256)"(
      token: string,
      numEth: BigNumberish,
      numToken: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    depositAndBuy(
      token: string,
      numToken: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "depositAndBuy(address,uint256,uint256)"(
      token: string,
      numToken: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    epoch(overrides?: CallOverrides): Promise<BigNumber>;

    "epoch()"(overrides?: CallOverrides): Promise<BigNumber>;

    estimateReward(
      owner: string,
      token: string,
      numEth: BigNumberish,
      numTokensSold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        profitablePrice: BigNumber;
        avgBlock: BigNumber;
        htrs: BigNumber;
        reward: BigNumber;
      }
    >;

    "estimateReward(address,address,uint256,uint256)"(
      owner: string,
      token: string,
      numEth: BigNumberish,
      numTokensSold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        profitablePrice: BigNumber;
        avgBlock: BigNumber;
        htrs: BigNumber;
        reward: BigNumber;
      }
    >;

    safeList(overrides?: CallOverrides): Promise<string>;

    "safeList()"(overrides?: CallOverrides): Promise<string>;

    sell(
      token: string,
      numToken: BigNumberish,
      numEthLimit: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "sell(address,uint256,uint256,uint256)"(
      token: string,
      numToken: BigNumberish,
      numEthLimit: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    sellAndWithdraw(
      token: string,
      numToken: BigNumberish,
      numEthLimit: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "sellAndWithdraw(address,uint256,uint256,uint256)"(
      token: string,
      numToken: BigNumberish,
      numEthLimit: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    tokenPriceData(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        ethSum: BigNumber;
        tokenSum: BigNumber;
        weightedBlockSum: BigNumber;
        latestBlock: BigNumber;
      }
    >;

    "tokenPriceData(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        ethSum: BigNumber;
        tokenSum: BigNumber;
        weightedBlockSum: BigNumber;
        latestBlock: BigNumber;
      }
    >;

    uniswapV3SwapCallback(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "uniswapV3SwapCallback(int256,int256,bytes)"(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    vnlContract(overrides?: CallOverrides): Promise<string>;

    "vnlContract()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    TokensPurchased(
      buyer: string | null,
      token: string | null,
      eth: null,
      amount: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      { buyer: string; token: string; eth: BigNumber; amount: BigNumber }
    >;

    TokensSold(
      seller: string | null,
      token: string | null,
      amount: null,
      eth: null,
      profit: null,
      reward: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        seller: string;
        token: string;
        amount: BigNumber;
        eth: BigNumber;
        profit: BigNumber;
        reward: BigNumber;
      }
    >;
  };

  estimateGas: {
    buy(
      token: string,
      numEth: BigNumberish,
      numToken: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "buy(address,uint256,uint256,uint256)"(
      token: string,
      numEth: BigNumberish,
      numToken: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositAndBuy(
      token: string,
      numToken: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "depositAndBuy(address,uint256,uint256)"(
      token: string,
      numToken: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    epoch(overrides?: CallOverrides): Promise<BigNumber>;

    "epoch()"(overrides?: CallOverrides): Promise<BigNumber>;

    estimateReward(
      owner: string,
      token: string,
      numEth: BigNumberish,
      numTokensSold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "estimateReward(address,address,uint256,uint256)"(
      owner: string,
      token: string,
      numEth: BigNumberish,
      numTokensSold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    safeList(overrides?: CallOverrides): Promise<BigNumber>;

    "safeList()"(overrides?: CallOverrides): Promise<BigNumber>;

    sell(
      token: string,
      numToken: BigNumberish,
      numEthLimit: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "sell(address,uint256,uint256,uint256)"(
      token: string,
      numToken: BigNumberish,
      numEthLimit: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sellAndWithdraw(
      token: string,
      numToken: BigNumberish,
      numEthLimit: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "sellAndWithdraw(address,uint256,uint256,uint256)"(
      token: string,
      numToken: BigNumberish,
      numEthLimit: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tokenPriceData(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "tokenPriceData(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    uniswapV3SwapCallback(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "uniswapV3SwapCallback(int256,int256,bytes)"(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    vnlContract(overrides?: CallOverrides): Promise<BigNumber>;

    "vnlContract()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    buy(
      token: string,
      numEth: BigNumberish,
      numToken: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "buy(address,uint256,uint256,uint256)"(
      token: string,
      numEth: BigNumberish,
      numToken: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositAndBuy(
      token: string,
      numToken: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "depositAndBuy(address,uint256,uint256)"(
      token: string,
      numToken: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    epoch(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "epoch()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    estimateReward(
      owner: string,
      token: string,
      numEth: BigNumberish,
      numTokensSold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "estimateReward(address,address,uint256,uint256)"(
      owner: string,
      token: string,
      numEth: BigNumberish,
      numTokensSold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    safeList(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "safeList()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sell(
      token: string,
      numToken: BigNumberish,
      numEthLimit: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "sell(address,uint256,uint256,uint256)"(
      token: string,
      numToken: BigNumberish,
      numEthLimit: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sellAndWithdraw(
      token: string,
      numToken: BigNumberish,
      numEthLimit: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "sellAndWithdraw(address,uint256,uint256,uint256)"(
      token: string,
      numToken: BigNumberish,
      numEthLimit: BigNumberish,
      blockTimeDeadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tokenPriceData(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokenPriceData(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    uniswapV3SwapCallback(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "uniswapV3SwapCallback(int256,int256,bytes)"(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    vnlContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "vnlContract()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
